# Generated by Django 5.0.1 on 2024-02-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MarketPlace", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="admin_status",
            field=models.TextField(
                blank=True,
                choices=[("approved", "Approved"), ("notApproved", "Notapproved")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
