# Generated by Django 5.0.3 on 2024-03-07 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MarketPlace", "0002_alter_product_admin_status_alter_product_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productcategory",
            name="thumbnail",
        ),
        migrations.AddField(
            model_name="productcategory",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="CategoryThumbnailImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.CharField(max_length=255)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MarketPlace.productcategory",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
    ]
