# Generated by Django 5.0.3 on 2024-03-18 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MarketPlace", "0004_remove_shop_company_remove_shop_merchant"),
        ("Shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Shop.shop"
            ),
        ),
        migrations.DeleteModel(
            name="Shop",
        ),
    ]
