# Generated by Django 5.0.3 on 2024-04-10 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0004_alter_userprofile_userrole"),
        ("MarketPlace", "0005_alter_product_shop_delete_shop"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="user",
        ),
        migrations.AddField(
            model_name="product",
            name="company",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="Accounts.company",
            ),
            preserve_default=False,
        ),
    ]
