# Generated by Django 5.0.3 on 2024-04-10 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0004_alter_userprofile_userrole"),
        ("MarketPlace", "0008_alter_product_category_alter_product_sub_category"),
        ("Shop", "0004_alter_shop_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Accounts.company",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Shop.shop",
            ),
        ),
    ]
