# Generated by Django 5.0.3 on 2024-04-10 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0004_alter_userprofile_userrole"),
        ("MarketPlace", "0009_alter_product_company_alter_product_shop"),
        ("Shop", "0004_alter_shop_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="MarketPlace.productcategory",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="company",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="Accounts.company",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="shop",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="Shop.shop"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="sub_category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="MarketPlace.productsubcategory",
            ),
            preserve_default=False,
        ),
    ]
