# Generated by Django 5.0.3 on 2024-04-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MarketPlace", "0010_alter_product_category_alter_product_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("In Stoke", "Instoke"),
                    ("Low Stoke", "Lowstoke"),
                    ("Out of Stoke", "Outofstoke"),
                ],
                max_length=25,
            ),
        ),
    ]
