# Generated by Django 5.0.3 on 2024-04-10 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MarketPlace", "0012_remove_productimage_url_productimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productfile",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_file",
                to="MarketPlace.product",
            ),
        ),
    ]
