# Generated by Django 5.0.3 on 2024-04-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MarketPlace", "0013_alter_productfile_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="productfile",
            name="file_description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
