# Generated by Django 5.0.3 on 2024-04-11 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MarketPlace", "0014_productfile_file_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productfile",
            name="file_description",
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="MarketPlace.product",
            ),
        ),
    ]
