# Generated by Django 5.0.3 on 2024-04-11 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MarketPlace", "0016_productimagethumbnail_productimagevariations_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productimagevariations",
            old_name="image",
            new_name="imageFile",
        ),
    ]
