# Generated by Django 5.0.3 on 2024-04-11 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MarketPlace", "0017_rename_image_productimagevariations_imagefile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productfile",
            old_name="file",
            new_name="product_file",
        ),
        migrations.RenameField(
            model_name="productimagethumbnail",
            old_name="thumbnail",
            new_name="product_thumbnail",
        ),
        migrations.RenameField(
            model_name="productimagevariations",
            old_name="imageFile",
            new_name="product_image",
        ),
    ]
