# Generated by Django 5.0.3 on 2024-04-12 11:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MarketPlace", "0018_rename_file_productfile_product_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimagethumbnail",
            name="product_thumbnail",
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name="productimagevariations",
            name="product_image",
            field=cloudinary.models.CloudinaryField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
