# Generated by Django 5.0.3 on 2024-04-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MarketPlace", "0021_product_product_thumbnail_alter_cart_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="currency",
            field=models.CharField(choices=[("ETB", "Etb")], max_length=10),
        ),
    ]
