# Generated by Django 5.0.4 on 2024-04-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MarketPlace", "0023_userproductinteraction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
