# Generated by Django 5.0.4 on 2024-04-25 06:42

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MarketPlace", "0024_alter_product_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimagevariations",
            name="product",
        ),
        migrations.AddField(
            model_name="product",
            name="product_file",
            field=models.FileField(blank=True, null=True, upload_to="product_files"),
        ),
        migrations.AddField(
            model_name="product",
            name="product_image2",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_image3",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_image4",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_image5",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_image6",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.DeleteModel(
            name="ProductFile",
        ),
        migrations.DeleteModel(
            name="ProductImageVariations",
        ),
    ]
