# Generated by Django 5.0.4 on 2024-05-15 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MarketPlace", "0027_alter_userproductinteraction_product_and_more"),
        ("Shop", "0006_remove_shop_shopadmin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="Shop.shop",
            ),
        ),
    ]
