# Generated by Django 5.0.4 on 2024-05-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MarketPlace", "0028_alter_product_shop"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="ave_rating",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
