# Generated by Django 5.0.4 on 2024-05-21 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MarketPlace", "0029_product_ave_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userproductrating",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userProductRating_set",
                to="MarketPlace.product",
            ),
        ),
    ]
