# Generated by Django 5.0.4 on 2024-05-22 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MarketPlace", "0030_alter_userproductrating_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
        migrations.RemoveField(
            model_name="order",
            name="subtotal",
        ),
        migrations.RemoveField(
            model_name="order",
            name="vat",
        ),
    ]
