# Generated by Django 5.0.4 on 2024-05-22 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0010_alter_company_companyadmin"),
        ("MarketPlace", "0031_remove_order_discount_remove_order_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="order_vat",
            new_name="order_tax",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="merchant",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="merchant_company",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orderItem_merchant",
                to="Accounts.company",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="is_deleted",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orderItems",
                to="MarketPlace.order",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="status",
            field=models.TextField(
                blank=True,
                choices=[
                    ("shipped", "En route"),
                    ("cancelled", "Cancelled"),
                    ("delivered", "Delivered"),
                ],
                null=True,
            ),
        ),
    ]
