# Generated by Django 5.0.1 on 2024-02-02 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email_address"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="staff_status"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="verified"),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="approved"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "managerFirstName",
                    models.CharField(max_length=30, verbose_name="first_name"),
                ),
                (
                    "managerMiddleName",
                    models.CharField(max_length=30, verbose_name="middle_name"),
                ),
                (
                    "managerLastName",
                    models.CharField(max_length=30, verbose_name="last_name"),
                ),
                (
                    "managerCountry",
                    models.CharField(
                        max_length=50, verbose_name="managers_location_country"
                    ),
                ),
                (
                    "managerRegion",
                    models.CharField(
                        max_length=50, verbose_name="managers_location_region"
                    ),
                ),
                (
                    "managerZone",
                    models.CharField(
                        max_length=50, verbose_name="managers_location_zone"
                    ),
                ),
                (
                    "managerWoreda",
                    models.CharField(
                        max_length=50, verbose_name="managers_location_woreda"
                    ),
                ),
                (
                    "managerKebele",
                    models.CharField(
                        max_length=50, verbose_name="managers_location_kebele"
                    ),
                ),
                (
                    "managerPhoneNumber",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="phone_number"
                    ),
                ),
                (
                    "userRole",
                    models.CharField(
                        choices=[("Seller", "Seller"), ("Buyer", "Buyer")],
                        max_length=25,
                        verbose_name="user_type",
                    ),
                ),
                ("managerRenewedIDFront", models.ImageField(upload_to="user_IDs/")),
                ("managerRenewedIDBack", models.ImageField(upload_to="user_IDs/")),
                (
                    "profilePic",
                    models.ImageField(
                        blank=True, null=True, upload_to="user_profile_pics/"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "companyName",
                    models.CharField(max_length=50, verbose_name="company_name"),
                ),
                (
                    "companyCountry",
                    models.CharField(
                        max_length=50, verbose_name="companys_location_country"
                    ),
                ),
                (
                    "companyRegion",
                    models.CharField(
                        max_length=50, verbose_name="companys_location_region"
                    ),
                ),
                (
                    "companyZone",
                    models.CharField(
                        max_length=50, verbose_name="companys_location_zone"
                    ),
                ),
                (
                    "companyWoreda",
                    models.CharField(
                        max_length=50, verbose_name="companys_location_woreda"
                    ),
                ),
                (
                    "companyKebele",
                    models.CharField(
                        max_length=50, verbose_name="companys_location_kebele"
                    ),
                ),
                ("companyHN", models.CharField(max_length=25, verbose_name="H_N")),
                ("companyTIN", models.CharField(max_length=25, verbose_name="TIN")),
                (
                    "companyPhoneNumber",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="phone_number"
                    ),
                ),
                ("companyLicense", models.ImageField(upload_to="company_licences/")),
                (
                    "companyLogo",
                    models.ImageField(
                        blank=True, null=True, upload_to="company_logos/"
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
    ]
