# Generated by Django 5.0.3 on 2024-04-03 12:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0002_alter_company_manager_alter_userprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="companyLicense",
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name="company",
            name="companyLogo",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="managerRenewedIDBack",
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="managerRenewedIDFront",
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profilePic",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True
            ),
        ),
    ]
