# Generated by Django 5.0.3 on 2024-04-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0003_alter_company_companylicense_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="userRole",
            field=models.CharField(
                choices=[("seller", "Seller"), ("buyer", "Buyer")],
                max_length=25,
                verbose_name="user_type",
            ),
        ),
    ]
