# Generated by Django 5.0.4 on 2024-04-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0004_alter_userprofile_userrole"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="manager",
            new_name="companyAdmin",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_approved",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_staff",
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_companyAdmin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_shopAdmin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
