# Generated by Django 5.0.4 on 2024-04-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0005_rename_manager_company_companyadmin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="companyCountry",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="company",
            name="companyHN",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="company",
            name="companyKebele",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="company",
            name="companyName",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="company",
            name="companyPhoneNumber",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="company",
            name="companyRegion",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="company",
            name="companyTIN",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="company",
            name="companyWoreda",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="company",
            name="companyZone",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="managerCountry",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="managerFirstName",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="managerKebele",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="managerLastName",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="managerMiddleName",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="managerPhoneNumber",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="managerRegion",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="managerWoreda",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="managerZone",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="userRole",
            field=models.CharField(
                choices=[("seller", "Seller"), ("buyer", "Buyer")], max_length=25
            ),
        ),
    ]
