# Generated by Django 5.0.4 on 2024-05-02 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "Accounts",
            "0006_alter_company_companycountry_alter_company_companyhn_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="managerCountry",
            new_name="userCountry",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="managerFirstName",
            new_name="userFirstName",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="managerKebele",
            new_name="userKebele",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="managerLastName",
            new_name="userLastName",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="managerMiddleName",
            new_name="userMiddleName",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="managerPhoneNumber",
            new_name="userPhoneNumber",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="managerRegion",
            new_name="userRegion",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="managerRenewedIDBack",
            new_name="userRenewedIDBack",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="managerRenewedIDFront",
            new_name="userRenewedIDFront",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="managerWoreda",
            new_name="userWoreda",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="managerZone",
            new_name="userZone",
        ),
    ]
