# Generated by Django 5.0.3 on 2024-03-18 08:00

import django.core.validators
import django.db.models.deletion
import helpers.fields
import helpers.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "logo",
                    helpers.fields.ValidatedImageField(
                        blank=True,
                        null=True,
                        upload_to="shop/logos",
                        validators=[
                            helpers.validators.ImageSizeValidator(5242880),
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=("png", "jpg", "jpeg", "jfif")
                            ),
                        ],
                    ),
                ),
                (
                    "cover_image",
                    helpers.fields.ValidatedImageField(
                        blank=True,
                        null=True,
                        upload_to="shop/cover_images",
                        validators=[
                            helpers.validators.ImageSizeValidator(5242880),
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=("png", "jpg", "jpeg", "jfif")
                            ),
                        ],
                    ),
                ),
                ("is_deleted", models.TextField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Accounts.company",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShopOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_owner",
                        to="Accounts.company",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
    ]
