# Generated by Django 5.0.3 on 2024-03-18 12:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="cover_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="logo",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True
            ),
        ),
    ]
