# Generated by Django 5.0.3 on 2024-04-03 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Shop", "0002_alter_shop_cover_image_alter_shop_logo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop",
            name="merchant",
        ),
    ]
