# Generated by Django 5.0.3 on 2024-04-04 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0004_alter_userprofile_userrole"),
        ("Shop", "0003_remove_shop_merchant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shops",
                to="Accounts.company",
            ),
        ),
    ]
