# Generated by Django 5.0.4 on 2024-05-08 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Shop", "0005_shop_shopadmin_delete_shopowner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop",
            name="shopAdmin",
        ),
    ]
